#!/usr/bin/env sh

CONTINUE=true
if [ -z "$PASSWORD" ]; then
	echo PASSWORD not set
	CONTINUE=false
fi
if [ -z "$PORT" ]; then
	echo PORT not set
	CONTINUE=false
fi
if [ -z "$USERNAME" ]; then
	echo USERNAME not set
	CONTINUE=false
fi
if [ -z "$HOSTNAME" ]; then
	echo HOSTNAME not set
	CONTINUE=false
fi
