#!/usr/bin/env sh

source get-credentials
if [ -f /var/www/html/wordpress.sql ]; then
  echo 'wordpress.sql already exists. Delete this file before running this download script.'
  exit 1
fi

if [ "$CONTINUE" = true ]; then
  echo 'downloading db'
  export LFTP_PASSWORD=$PASSWORD
  lftp -e 'get /wp-content/mysql.sql -o /var/www/html/wordpress.sql; bye' --env-password  sftp://$USERNAME@$HOSTNAME:$PORT
else
  Missing SFTP credentials. Not doing anything.
fi
