#!/usr/bin/env sh

source /sftp-config

CONTINUE=true
if [ -z "$PASSWORD" ]; then
	echo PASSWORD not set
	CONTINUE=false
fi
if [ -z "$PORT" ]; then
	echo PORT not set
	CONTINUE=false
fi
if [ -z "$USERNAME" ]; then
	echo USERNAME not set
	CONTINUE=false
fi
if [ -z "$HOSTNAME" ]; then
	echo HOSTNAME not set
	CONTINUE=false
fi

if [ -z "$REMOTE_PREFIX" ]; then
	REMOTE_PREFIX=''
fi
if [ -z "$LOCAL_PREFIX" ]; then
	LOCAL_PREFIX='/var/www/html'
fi
