#!/usr/bin/env sh

local=`wp option get siteurl`
echo 'importing wordpress.sql database file'
wp db import
remote=`wp option get siteurl`

echo "replacing $remote with $local in database"
wp search-replace $remote $local
echo 'import complete'
