#!/usr/bin/env sh

if $(wp core is-installed); then
	echo 'WP Core is installed.'
	local=`wp option get siteurl`
else
	local=http://${LOCAL_DEV_DOMAIN-localhost}
fi

echo 'Importing wordpress.sql database file.'
wp db import
remote=`wp option get siteurl`

echo "Replacing $remote with $local in database."
wp search-replace $remote $local

echo "Setting mangrove-team password to 'localpass'."
wp user update mangrove-team --user_pass=localpass --skip-email

echo 'Deactivating plugins known to cause issues on local dev. An error is expected if these plugins are not installed.'
wp plugin deactivate better-wp-security ithemes-security-pro block-bad-queries --quiet

echo 'Import complete.'
