#!/usr/bin/env sh
echo Initializing WordPress Install
wp core install \
	--url='localhost' --title='Local WordPress' \
	--admin_user='test' \
	--admin_password='test' \
	--admin_email='wp@mangrove-web.com' --skip-email
if [ "$?" = "0" ]; then
	echo WordPress initialized.
	echo http://localhost
	echo Admin
	echo username: test
	echo password: test
else
	printf "\nCouldn't install WordPress. Wait for the WordPress container to finish setting up and try again.\n"
fi
